stages:
  - security_check
  - code_quality

.job-dependency:
  image: ghcr.io/cirruslabs/flutter:3.24.5
  allow_failure: true


dependency-check:
  stage: security_check
  extends: .job-dependency
  before_script:
    - flutter pub get
  script:
    - flutter pub outdated
  after_script:
    - echo "Dependency check completed successfully"


flutter-lint:
  stage: code_quality
  extends: .job-dependency
  before_script:
    - flutter pub get
  script:
    - flutter analyze
  after_script:
    - echo "Flutter linting completed successfully"


vulnerability-check:
  stage: security_check
  extends: .job-dependency
  before_script:
    - pip install safety
  script:
    - safety check -r ./pubspec.lock
  after_script:
    - echo "Vulnerability check completed successfully"
